# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        self.date = None
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1079, 717)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_city = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_city.setGeometry(QtCore.QRect(30, 30, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_city.setFont(font)
        self.comboBox_city.setObjectName("comboBox_city")
        # self.comboBox_city.addItem("")
        # self.comboBox_city.addItem("")
        self.comboBox_laguage = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_laguage.setGeometry(QtCore.QRect(30, 130, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_laguage.setFont(font)
        self.comboBox_laguage.setObjectName("comboBox_laguage")
        # self.comboBox_laguage.addItem("")
        # self.comboBox_laguage.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(750, 90, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"border: 2px, solid, #223344;\n"
"border-radius: 20;")
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 230, 681, 451))
        self.textBrowser.setObjectName("textBrowser")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(370, 20, 312, 183))
        self.calendarWidget.setObjectName("calendarWidget")
        self.calendarWidget.clicked.connect(self.calendar_click)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1079, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Список вакансий"))
        # self.comboBox_city.setItemText(0, _translate("mainWindow", "kyiv"))
        # self.comboBox_city.setItemText(1, _translate("mainWindow", "odesa"))
        # self.comboBox_laguage.setItemText(0, _translate("mainWindow", "python"))
        # self.comboBox_laguage.setItemText(1, _translate("mainWindow", "php"))
        self.pushButton.setText(_translate("mainWindow", "Получить данные"))

    def calendar_click(self):
        self.date = self.calendarWidget.selectedDate()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
